### ISSUE TITLE
Toggle between daily and hourly forcast

### ISSUE THREAD

**Issue by PAOK-2001** [MLH-Fellowship/prep-project-22.P3.1#14]
A team is currently working on the hourly forcast. It would be nice to hace a daily forcast as well and be able  to change between forcasts.

![Issue2](https://user-images.githubusercontent.com/29895011/162813032-a4f530fa-def2-4e82-aa69-3d92ea1bcb7d.png)
.

**Comment by PAOK-2001** [comment]
Me and @Mayank17M

**Comment by Mayank17M** [comment]
@yashika51 this can also be closed
#65
