### ISSUE TITLE
Change the colour scheme based on temperature / weather type

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-22.P3.1#2]
Change the websites appearance to match the weather conditions. The Apple Weather app has some cool examples in iOS 15, check them out [here](https://9to5mac.com/2021/09/24/ios-15-weather-app-hands-on/).

**Comment by suraj-singh127** [comment]
Me and @n00bmaster2810 would like to work on this.

**Comment by Mayank17M** [comment]
#29 fixes this issue. 
@yashika51 this can be closed.
