### ISSUE TITLE
.eslintcache file should be in the node modules folder and should be ignored

### ISSUE THREAD

**Issue by suraj-singh127** [MLH-Fellowship/prep-project-22.P3.1#30]
.eslintcache file keeps getting generated even after trying the various available method to .gitignore this file, the files keeps generating.
As of now the only viable solutions seems to be deleting the .eslintcache file and then push the changes upstream.

Here is a reference of this issue - https://github.com/facebook/create-react-app/pull/9977

can you guys please look into this issue and confirm if this happens on your devices as well?

**Comment by Mutugiii** [comment]
Adding it to the .gitignore should be sufficient since it remains untracked

**Comment by yashika51** [comment]
Yeah I think .`gitignore` should handle it if the `gitignore` file and the `cache` file are in the same directory. @suraj-singh127

**Comment by Mayank17M** [comment]
@yashika51 this can be closed
