### ISSUE TITLE
Edge Case Handling for showing weather data

### ISSUE THREAD

**Issue by ankitaugale23** [MLH-Fellowship/prep-project-22.P3.1#37]
![bug_MLH_week_2](https://user-images.githubusercontent.com/58697646/163685914-9eeb9101-2712-44b9-a3bc-1a57a0d5059c.png)

> Case1: Once the user allows the geolocation while the API is fetching that data this city's data is showing(attached in  the image)
>Case2: When the user does not allow the geolocation, the default city shown should be New York, but while its data is getting fetched, still the same city's  data is shown

Please assign this issue to @ankitaugale23 and @JyotimoyKashyap

**Comment by JyotimoyKashyap** [comment]
@ankitaugale23 I guess this issue can be closed as it has been handled in recent PRs.
