### ISSUE TITLE
Food Recommendations depending on the weather.

### ISSUE THREAD

**Issue by suraj-singh127** [MLH-Fellowship/prep-project-22.P3.1#45]
A food recommendation system for recommending users food/drinks on the basis of weather conditions.
Generic food and drinks like Coffee/Chai for Rainy weather, fruit salad or a healthy juice for Sunny, Hot Chocolate or Hot Coffee for cold weather. These recommendations can also be user's location specific.

**Comment by JyotimoyKashyap** [comment]
Me and @ankitaugale23 would like to work on it.
