### ISSUE TITLE
Map for selecting location

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-22.P3.1#5]
Instead of just typing the location in, display a map to the user (using OpenStreetMap for example), and take the coordinates of their pin and use that to display weather information.

Make it a 2 way thing, and if a user types a location in, it displays a pin on the map as well!

If you have an API key, let @wrussell1999 know so it can be added to the Netlify website hosting it!

**Comment by Mayank17M** [comment]
Me and @PAOK-2001 will take this on.
