### ISSUE TITLE
Music Recommender enhances and edge cases

### ISSUE THREAD

**Issue by Mutugiii** [MLH-Fellowship/prep-project-22.P3.1#58]
Work on a few edge cases and enhancements for the music recommender

- [x] Work on the initialization issue and bad API calls
- [ ] Automatically stop music playing for an already running audio card when another audio card starts playings
- [ ] Add a loader for when changing the layouts
- [ ] Put a loader in place for song cards(or hide it) when the weather API is loading
- [ ] Show more button/Pagination to allow more songs to show up, currently the limit is 6
- [ ] UI enhancements where possible - Particularly for the preference cards

**Comment by Mutugiii** [comment]
@OmkarAcharekar and I will be working on this. Anyone else who wishes to help out/join in, feel free to ping us

cc: @yashika51

**Comment by JyotimoyKashyap** [comment]
@Mutugiii can you convert those into tasks so that we can get an idea about what tasks are left in this issue.

**Comment by Mutugiii** [comment]
Thanks for the suggestion @JyotimoyKashyap I've done that!

**Comment by OmkarAcharekar** [comment]
@JyotimoyKashyap please comment the issue if you are working on any..

**Comment by Mutugiii** [comment]
Currently, I am working on task 5, Omkar is working on task 4, and we are looking into fixes for task 2

**Comment by n00bmaster2810** [comment]
I can work for the 3rd one.

**Comment by KKhushhalR2405** [comment]
Hey, @Mutugiii @OmkarAcharekar I am planning to work on task 6. Is there anything specific I should keep in mind?

**Comment by Mutugiii** [comment]
@KKhushhalR2405 not really, feel free to be creative
