### ISSUE TITLE
Autocomplete for cities

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/prep-project-22.P3.1#6]
At the moment, when you type in a city, it won't help you finish your entry with suggestions. A cool feature would be if it had a drop down menu that suggested locations similar to the name. For example, if I type in `Cambridge`, it could tell me `Cambridge, MA, USA` or `Cambridge, UK` to help users get the right answers!

**Comment by n00bmaster2810** [comment]
@suraj-singh127 and I can work on this.

**Comment by n00bmaster2810** [comment]
@yashika51 please close this as it got merged.
