### ISSUE TITLE
[Feature] Toggle to return to user's location 

### ISSUE THREAD

**Issue by JyotimoyKashyap** [MLH-Fellowship/prep-project-22.P3.1#60]
#### Problem: 
In the current state of the website, the user's location is fetched at the start, but if the user starts exploring different cities then there's is no option to return to their original location. 

#### Solution: 
The solution to this problem is to add a toggle or icon to the right side of the search city field, that would allow the user to return to their location.

**Comment by AnushaNathRoy** [comment]
Hey! can @shamvi-05 and I work on this issue?

**Comment by JyotimoyKashyap** [comment]
> Hey! can @shamvi-05 and I work on this issue?

Yeah sure, you can work on this.
