### ISSUE TITLE
[Bug] Weather Card content overflow

### ISSUE THREAD

**Issue by KKhushhalR2405** [MLH-Fellowship/prep-project-22.P3.1#63]
Weather card overflowing components need to be fixed.

<img width="319" alt="164287131-ef36d2f3-5496-4fea-abe7-4d41e53ceec7" src="https://user-images.githubusercontent.com/58569950/164289349-56ee3e37-f818-4bf8-841c-902875d701cc.png">

**Comment by PAOK-2001** [comment]
This is fixed in Suraj's latest PR (#64) it isn't an issue with the weather card rather than the background image. Suraj choose longer images to prevent it from happening.

**Comment by KKhushhalR2405** [comment]
Sounds great🥳. Closing the issue
