### ISSUE TITLE
Remove the news section for now as the News API doesn't support free services globally

### ISSUE THREAD

**Issue by suraj-singh127** [MLH-Fellowship/prep-project-22.P3.1#68]
The last pull request that I made doesn't integrate the News on the page because the News API after 20 May, 2022 changed it's policy to allow API calls only to localhost and not globally.

Here's a blog post related to the issue - https://answers.netlify.com/t/getting-error-426-from-newsapi-org/16101/4

**Comment by shamvi-05** [comment]
PR #75 adds Static data to the News Section as discussed so I think this fixes this issue.
