### ISSUE TITLE
[Bug] Fixing Navbar links

### ISSUE THREAD

**Issue by KKhushhalR2405** [MLH-Fellowship/prep-project-22.P3.1#71]
Currently, the Nav Links are just redirecting to the home page. It should be changed so that they redirect to that particular part in the webpage.

**Comment by KKhushhalR2405** [comment]
This issue is up for grab ✊

**Comment by suraj-singh127** [comment]
I am currently working on fixing this.

**Comment by KKhushhalR2405** [comment]
> I am currently working on fixing this.

Hi suraj, in yesterday's standup pablo did mention that his PR will fix this. @PAOK-2001 can you please confirm.

**Comment by KKhushhalR2405** [comment]
I just checked and this issue was solved in #65.
